# Generated by Django 2.1.8 on 2019-07-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='goods_id',
            field=models.IntegerField(verbose_name='商品id'),
        ),
    ]
