# Generated by Django 2.1.8 on 2019-07-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_auto_20190728_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='goods_num',
            field=models.IntegerField(verbose_name='商品数量'),
        ),
    ]
