# Generated by Django 2.1.8 on 2019-07-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0006_order_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='goods_image',
            field=models.IntegerField(default=1, verbose_name='商品图片'),
            preserve_default=False,
        ),
    ]
