# Generated by Django 2.1.8 on 2019-07-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0008_auto_20190729_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='goods_image',
            field=models.ImageField(upload_to='', verbose_name='商品图片'),
        ),
    ]
