# Generated by Django 2.1.8 on 2019-07-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0010_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='goods_num',
            new_name='goods_number',
        ),
        migrations.AddField(
            model_name='cart',
            name='goods_store',
            field=models.IntegerField(default=1, verbose_name='商品商店'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='goods_total',
            field=models.FloatField(default=1, verbose_name='商品总价'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='goods_picture',
            field=models.ImageField(upload_to='buyer/images', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='goods_price',
            field=models.FloatField(verbose_name='商品价格'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.IntegerField(verbose_name='用户id'),
        ),
    ]
