# Generated by Django 2.1.8 on 2019-07-30 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0011_auto_20190730_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='user_id',
        ),
    ]
